import { isProtoEnum, isProtoMessage, ProtoEnum, ProtoField, ProtoMessage } from "./proto-dsl"

export function generateProtoFile(names: Map<string, ProtoMessage | ProtoEnum>): string {
  const parts: string[] = [`// THIS FILE IS AUTOGENERATED`, `syntax = "proto3";`]

  for (const [name, value] of names) {
    if (isProtoMessage(value)) {
      parts.push(`message ${name} {`)

      value.fields.sort((a, b) => (a.number > b.number ? 1 : -1))

      for (const field of value.fields) {
        parts.push(`  ${field.repeated ? "repeated " : ""}${field.type}\t${field.name} = ${field.number};`)
      }

      parts.push(`}\n`)
    } else if (isProtoEnum(value)) {
      parts.push(`enum ${name} {`)
      for (const key in value.values) {
        parts.push(`  ${name}_${key} = ${value.values[key]};`)
      }
      parts.push(`}\n`)
    }
  }

  return parts.join("\n")
}
